name: docker-build

on:
  push:
    branches: [master, develop]

jobs:
  docker-build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Build container dev
        run: docker build -t first-electric/api:develop .
        if: contains('refs/heads/develop',github.ref)
      - name: Build container prod
        run: docker build -t first-electric/api:master .
        if: contains('refs/heads/master',github.ref)
      - name: Reload containers
        run: docker-compose -f /docker/compose/docker-compose.yml up -d

